# Generated by Django 4.0 on 2021-12-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('matid', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=255)),
                ('Cf', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('pasw', models.CharField(max_length=255)),
            ],
        ),
    ]
