# Generated by Django 4.0.4 on 2022-06-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_users_delete_coders'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
