# Generated by Django 4.0.4 on 2022-06-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1040)),
                ('area', models.CharField(max_length=255)),
                ('rentfare', models.CharField(max_length=255)),
                ('bedroom', models.CharField(max_length=255)),
                ('bathroom', models.CharField(max_length=255)),
                ('parking', models.CharField(max_length=255)),
                ('contactnumber', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
