# Generated by Django 4.0.4 on 2022-06-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_posts_options_alter_posts_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='posts',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='posts',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='posts',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='posts',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
