# Generated by Django 4.0.4 on 2022-06-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_photo_posts_photo1_posts_photo2_posts_photo3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='usid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
