# Generated by Django 4.0.4 on 2022-06-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_posts_usid'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='postid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
