# Generated by Django 4.0.4 on 2022-06-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_posts_rentfare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='bathroom',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='bedroom',
            field=models.IntegerField(),
        ),
    ]
